#!/bin/sh
#This script tested on ubuntu 12.04 LTS

echo "installing dkms"
sudo apt-get install dkms

sudo ln -s `pwd` /usr/src/hid-a320-0.1

echo "compiling module"
sudo dkms add -m hid-a320 -v 0.1
sudo dkms build -m hid-a320 -v 0.1
sudo dkms install -m hid-a320 -v 0.1

grep -q "hid-a320" /etc/initramfs-tools/modules
if [ $? -ne 0 ] ; then
    echo "Adding hid-a320 to /etc/initramfs-tools/modules"
    sudo sh -c "echo hid-a320 >> /etc/initramfs-tools/modules"
fi
echo "Generating initrd"
sudo update-initramfs -u

echo "Done"
