#!/bin/sh

echo "Compiling"
make clean
make
sudo make install
echo "Reloading module"
sudo modprobe -r usbhid;
sudo modprobe -r hid-a320;
sudo modprobe hid-a320;
sudo modprobe usbhid;
grep -q "hid-a320" /etc/initramfs-tools/modules
if [ $? -ne 0 ] ; then
    echo "Adding hid-a320 to /etc/initramfs-tools/modules"
    sudo sh -c "echo hid-a320 >> /etc/initramfs-tools/modules"
fi
sudo update-initramfs -u
